version: '3'
services:
  letsencrypt:
    build:
      context: .
      dockerfile: lets_encrypt.Dockerfile
    volumes:
      - "/letsencrypt:/etc/letsencrypt/"
      - "/letsencrypt_var_log:/var/log/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
